apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: weewx
    app.kubernetes.io/name: weewx
  name: weewx-data
  namespace: weewx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-nfs-bulk
  volumeMode: Filesystem
