apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Internal Registry for OKD
    openshift.io/display-name: Project-Quay
    openshift.io/requester: killerclaffey
    openshift.io/sa.scc.mcs: s0:c31,c5
    openshift.io/sa.scc.supplemental-groups: 1000940000/10000
    openshift.io/sa.scc.uid-range: 1000940000/10000
    security.openshift.io/MinimallySufficientPodSecurityStandard: restricted
  labels:
    kubernetes.io/metadata.name: quay
    olm.operatorgroup.uid/e3f8e223-8931-42ff-82e8-48d5e4efab7b: ''
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: quay
spec:
  finalizers:
  - kubernetes
