apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-credentials
  namespace: paperless-ngx
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-credentials
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: homelab/paperless-ngx
        property: secret-key
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: homelab/paperless-ngx
        property: admin-user
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: homelab/paperless-ngx
        property: admin-password
    - secretKey: PAPERLESS_ADMIN_EMAIL
      remoteRef:
        key: homelab/paperless-ngx
        property: admin-email
