apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-valkey
  namespace: paperless-ngx
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: tns-nvmeof-nvme
  volumeMode: Filesystem
