apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-bulk
  resources:
    requests:
      storage: 10Gi
