apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: 9router
    app.kubernetes.io/name: 9router
  name: 9router-data
  namespace: 9router
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-nfs-bulk
  volumeMode: Filesystem
