apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx
  namespace: nextcloud-fpm
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nextcloud-fpm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx
