apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: nextcloud-fpm
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nextcloud-fpm
