apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-auto-healer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/instance: argocd
spec:
  destination:
    namespace: csi-auto-healer
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/csi-auto-healer
    repoURL: https://gitlab.apps.okd.claffey.cloud/rclaffey/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
