apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  labels:
    app.kubernetes.io/instance: argocd
spec:
  destination:
    namespace: gitlab-runner
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gitlab-runner
    repoURL: https://charts.gitlab.io
    targetRevision: 0.73.1
    helm:
      values: |
        gitlabUrl: https://gitlab.apps.okd.claffey.cloud/
        unregisterRunners: false
        envVars:
          - name: HOME
            value: /home/gitlab-runner
        rbac:
          create: true
        runners:
          secret: gitlab-runner-secret
          config: |
            [[runners]]
              [runners.kubernetes]
                namespace = "gitlab-runner"
                image = "alpine:latest"
                privileged = false
                environment = ["HOME=/tmp"]
        securityContext:
          runAsUser: null
        podSecurityContext:
          fsGroup: null
          runAsUser: null
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
