apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - bikely-dev.yaml
  - bikely.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - gitlab-system.yaml
  - immich.yaml
  - mealie.yaml
  - monitoring.yaml
  - quay.yaml
  - rook-ceph.yaml
  - truenas-csi.yaml
  - tns-csi-configs.yaml
  - tns-csi-driver.yaml
  - uptime-kuma.yaml
  - vault.yaml
  - velero.yaml
  - homepage.yaml
  - stirling-pdf.yaml
  - renovate.yaml
  - stackrox.yaml
  - homeassistant.yaml

