apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-hardening
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://gitlab.apps.okd.claffey.cloud/rclaffey/homelab.git
    targetRevision: HEAD
    path: kubernetes/platform-hardening
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
