apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/instance: argocd
spec:
  destination:
    namespace: renovate
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/renovate/overlays/okd
    repoURL: https://gitlab.apps.okd.claffey.cloud/rclaffey/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - CreateNamespace=true
