apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thunderbolt-network
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.apps.okd.claffey.cloud/rclaffey/homelab.git
    targetRevision: HEAD
    path: kubernetes/thunderbolt-network
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
