apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://gitlab.apps.okd.claffey.cloud/rclaffey/homelab.git
    targetRevision: HEAD
    path: kubernetes/velero/overlays/okd
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: velero-credentials
      jsonPointers:
        - /data
