---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - cronjob-cron.yaml
  - cronjob-preview.yaml
  - pdb.yaml
  - hpa.yaml
  - network-policy.yaml
