apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service.yaml
  - route.yaml
  - deployment.yaml
  - configmap-settings.yaml
  - configmap-widgets.yaml
  - configmap-bookmarks.yaml
  - configmap-services.yaml
