apiVersion: v1
data:
  BASE_URL: https://mealie.apps.okd.claffey.cloud
  FORWARDED_ALLOW_IPS: '*'
  LOG_LEVEL: debug
  OIDC_AUTH_ENABLED: 'true'
  OIDC_AUTO_REDIRECT: 'false'
  OIDC_CLIENT_ID: 145432130559-i1fe197dmlspuka8eupj4idbu6is6k1n.apps.googleusercontent.com
  OIDC_CONFIGURATION_URL: https://accounts.google.com/.well-known/openid-configuration
  OIDC_PROVIDER_NAME: Google
  OIDC_SIGNUP_ENABLED: 'true'
  OPENAI_ENABLE_IMAGE_SERVICES: 'true'
  OPENAI_MODEL: gpt-5-mini-2025-08-07
  TZ: UTC
kind: ConfigMap
metadata:
  name: mealie-config
  namespace: mealie
