apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: mealie
    meta.helm.sh/release-namespace: mealie
  labels:
    app.kubernetes.io/instance: mealie
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mealie
    app.kubernetes.io/version: v1.0.0beta-2
    helm.sh/chart: mealie-5.1.2
  name: mealie-api-data
  namespace: mealie
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-nfs-bulk
  volumeMode: Filesystem
