apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-bookmarks
  namespace: homepage
data:
  bookmarks.yaml: |
    - Git:
        - GitHub Homelab:
            - icon: github
              href: https://github.com/killerclaffey/homelab
        - GitLab Server:
            - icon: gitlab
              href: https://gitlab.apps.okd.claffey.cloud
