apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: homepage
data:
  settings.yaml: |
    title: HomeLab Portal
    theme: dark
    layout:
      Core Cluster:
        columns: 3
      Developer Tools:
        columns: 3
      Observability:
        columns: 5
      Home Applications:
        columns: 4
