apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-widgets
  namespace: homepage
data:
  widgets.yaml: |
    - logo:
        icon: heartbeat
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hour12: true
    - search:
        provider: google
        target: _blank
