apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-bookmarks
  namespace: homepage
data:
  bookmarks.yaml: |
    - Git:
        - GitHub Homelab:
            abbr: GH
            icon: si-github
            href: https://github.com/killerclaffey/homelab
            description: HomeLab GitOps Repository
        - GitLab Server:
            abbr: GL
            icon: si-gitlab
            href: https://gitlab.apps.okd.claffey.cloud
            description: Self-hosted GitLab Instance
