apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: ''
    openshift.io/requester: killerclaffey
    openshift.io/sa.scc.mcs: s0:c28,c22
    openshift.io/sa.scc.supplemental-groups: 1000800000/10000
    openshift.io/sa.scc.uid-range: 1000800000/10000
    security.openshift.io/MinimallySufficientPodSecurityStandard: baseline
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bikely
    deployment: okd
    environment: production
    kubernetes.io/metadata.name: bikely
    name: bikely
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: bikely
spec:
  finalizers:
  - kubernetes
