---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: homeassistant-cert
  labels:
    app.kubernetes.io/instance: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      name: https
  type: ClusterIP

