apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-gitlab-controller-manager-yaml
- namespace.yaml
- pvc-data-gitlab-postgresql-0-yaml
- pvc-redis-data-gitlab-redis-master-0-yaml
- pvc-repo-data-gitlab-gitaly-0-yaml
- service-gitlab-controller-manager-metrics-service-yaml
- service-gitlab-webhook-service-yaml
