apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-prometheus-stack-grafana-config-dashboards-yaml
- configmap-prometheus-stack-grafana-yaml
- configmap-prometheus-stack-kube-prom-alertmanager-overview-yaml
- configmap-prometheus-stack-kube-prom-apiserver-yaml
- configmap-prometheus-stack-kube-prom-cluster-total-yaml
- configmap-prometheus-stack-kube-prom-controller-manager-yaml
- configmap-prometheus-stack-kube-prom-etcd-yaml
- configmap-prometheus-stack-kube-prom-grafana-datasource-yaml
- configmap-prometheus-stack-kube-prom-grafana-overview-yaml
- configmap-prometheus-stack-kube-prom-k8s-coredns-yaml
- configmap-prometheus-stack-kube-prom-k8s-resources-cluster-yaml
- configmap-prometheus-stack-kube-prom-k8s-resources-multicluster-yaml
- configmap-prometheus-stack-kube-prom-k8s-resources-namespace-yaml
- configmap-prometheus-stack-kube-prom-k8s-resources-node-yaml
- configmap-prometheus-stack-kube-prom-k8s-resources-pod-yaml
- configmap-prometheus-stack-kube-prom-k8s-resources-workload-yaml
- configmap-prometheus-stack-kube-prom-k8s-resources-workloads-namespace-yaml
- configmap-prometheus-stack-kube-prom-kubelet-yaml
- configmap-prometheus-stack-kube-prom-namespace-by-pod-yaml
- configmap-prometheus-stack-kube-prom-namespace-by-workload-yaml
- configmap-prometheus-stack-kube-prom-node-cluster-rsrc-use-yaml
- configmap-prometheus-stack-kube-prom-node-rsrc-use-yaml
- configmap-prometheus-stack-kube-prom-nodes-aix-yaml
- configmap-prometheus-stack-kube-prom-nodes-darwin-yaml
- configmap-prometheus-stack-kube-prom-nodes-yaml
- configmap-prometheus-stack-kube-prom-persistentvolumesusage-yaml
- configmap-prometheus-stack-kube-prom-pod-total-yaml
- configmap-prometheus-stack-kube-prom-prometheus-yaml
- configmap-prometheus-stack-kube-prom-proxy-yaml
- configmap-prometheus-stack-kube-prom-scheduler-yaml
- configmap-prometheus-stack-kube-prom-workload-total-yaml
- daemonset-prometheus-stack-prometheus-node-exporter-yaml
- deployment-prometheus-stack-grafana-yaml
- deployment-prometheus-stack-kube-prom-operator-yaml
- deployment-prometheus-stack-kube-state-metrics-yaml
- namespace.yaml
- pvc-alertmanager-prometheus-stack-kube-prom-alertmanager-db-alertmanager-prometheus-stack-kube-prom-alertmanager-0-yaml
- pvc-prometheus-prometheus-stack-kube-prom-prometheus-db-prometheus-prometheus-stack-kube-prom-prometheus-0-yaml
- route-prometheus-stack-grafana-yaml
- route-prometheus-stack-kube-prom-alertmanager-yaml
- route-prometheus-stack-kube-prom-prometheus-yaml
- service-prometheus-stack-grafana-yaml
- service-prometheus-stack-kube-prom-alertmanager-yaml
- service-prometheus-stack-kube-prom-operator-yaml
- service-prometheus-stack-kube-prom-prometheus-yaml
- service-prometheus-stack-kube-state-metrics-yaml
- service-prometheus-stack-prometheus-node-exporter-yaml
