apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stackrox-admin-password
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: stackrox-admin-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: homelab/stackrox/common
        property: admin-password
