apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-bikely-config-yaml
- configmap-nginx-config-yaml
- deployment-bikely-backend-yaml
- deployment-bikely-frontend-yaml
- deployment-bikely-upload-service-yaml
- deployment-postgres-yaml
- namespace.yaml
- pvc-postgres-backup-pvc-yaml
- pvc-postgres-pvc-yaml
- route-bikely-dev-api-yaml
- route-bikely-dev-main-yaml
- route-bikely-dev-upload-yaml
- service-bikely-backend-service-yaml
- service-bikely-frontend-service-yaml
- service-bikely-upload-service-yaml
- service-postgres-yaml
