---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeassistant-cert
  namespace: homeassistant
  labels:
    app.kubernetes.io/instance: homeassistant
spec:
  secretName: homeassistant-cert
  duration: 1080h # 45d
  renewBeforePercentage: 50
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  dnsNames:
    - "home.apps.okd.claffey.cloud"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
