apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-truenas-csi-config-yaml
- daemonset-truenas-csi-node-yaml
- deployment-truenas-csi-controller-yaml
- namespace.yaml
- pvc-test-yaml
